pkg/deb/init.d/jobmond:
 * working init.d script

diff --git a/trunk/pkg/deb/init.d/jobmond b/trunk/pkg/deb/init.d/jobmond
--- a/trunk/pkg/deb/init.d/jobmond
+++ b/trunk/pkg/deb/init.d/jobmond
@@ -5,22 +5,26 @@ DAEMON=/usr/bin/jobmond
 NAME=jobmond
 DESC="Job Monitor Daemon"
 
+PIDFILE="/var/run/jobmond.pid"
+
 test -x $DAEMON || exit 0
 
-set -e
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 case "$1" in
   start)
 	echo -n "Starting $DESC: "
-	start-stop-daemon --start --quiet -m --pidfile /var/run/$NAME.pid \
-		--exec $DAEMON 
+	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
+		--exec $DAEMON -- --pidfile "$PIDFILE" || { echo " start failed."; exit 1; }
 	echo "$NAME."
 	;;
   stop)
 	echo -n "Stopping $DESC: "
-        start-stop-daemon --stop  --quiet --oknodo --name $DAEMON \
-                2>&1 > /dev/null
+        start-stop-daemon --stop  --quiet --pidfile /var/run/$NAME.pid \
+                --signal 9 2>&1 > /dev/null || { rm -f "$PIDFILE"; echo " not running."; exit 1; }
 	echo "$NAME."
+	rm -f "$PIDFILE"
+	exit 0
 	;;
   restart|force-reload)
 	$0 stop
