* pkg bla

diff --git a/trunk/pkg/deb/init.d/jobmond b/trunk/pkg/deb/init.d/jobmond
--- a/trunk/pkg/deb/init.d/jobmond
+++ b/trunk/pkg/deb/init.d/jobmond
@@ -17,13 +17,13 @@ case "$1" in
   start)
 	echo -n "Starting $DESC: "
 	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
-		--exec $DAEMON -- --pidfile "$PIDFILE" $OPTIONS || { echo " start failed."; exit 0; }
+		--exec $DAEMON -- --pidfile "$PIDFILE" $OPTIONS || { echo "start failed."; exit 0; }
 	echo "$NAME."
 	;;
   stop)
 	echo -n "Stopping $DESC: "
         start-stop-daemon --stop  --quiet --pidfile /var/run/$NAME.pid \
-                --signal 9 2>&1 > /dev/null || { rm -f "$PIDFILE"; echo " not running."; exit 0; }
+                --signal 9 2>&1 > /dev/null || { rm -f "$PIDFILE"; echo "not running."; exit 0; }
 	echo "$NAME."
 	rm -f "$PIDFILE"
 	exit 0
