pkg/deb/init.d/jobmond:
 * removed "return"

diff --git a/pkg/deb/init.d/jobmond b/pkg/deb/init.d/jobmond
--- a/pkg/deb/init.d/jobmond
+++ b/pkg/deb/init.d/jobmond
@@ -17,13 +17,13 @@ case "$1" in
   start)
 	echo -n "Starting $DESC: "
 	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
-		--exec $DAEMON -- --pidfile "$PIDFILE" $OPTIONS || { echo "start failed."; return 0; }
+		--exec $DAEMON -- --pidfile "$PIDFILE" $OPTIONS || { rm -f "$PIDFILE"; echo "start failed." }
 	echo "$NAME."
 	;;
   stop)
 	echo -n "Stopping $DESC: "
         start-stop-daemon --stop  --quiet --pidfile /var/run/$NAME.pid \
-                --signal 9 2>&1 > /dev/null || { rm -f "$PIDFILE"; echo "not running."; return 0; }
+                --signal 9 2>&1 > /dev/null || { rm -f "$PIDFILE"; echo "not running." }
 	echo "$NAME."
 	rm -f "$PIDFILE"
 	exit 0
